import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import theme from '@/lib/theme';
import { CssBaseline, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { SWRProvider } from './swr-provider'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  style: ['normal', 'italic'],
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--font-roboto',
  preload: true,
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AppRouterCacheProvider options={{ key: 'css' }}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <SWRProvider>
              {children}
            </SWRProvider>
           </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
